<?php

use Illuminate\Database\Seeder;

class Cg_picture_MastersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cg_picture_masters')->insert([
            ['id' => '1',
            'path' => 'cg1.jpg',
            ],
            ['id' => '2',
            'path' => 'cg2.jpg',
            ],
            ['id' => '3',
            'path' => 'cg3.jpg',
            ],
            ['id' => '4',
            'path' => 'cg4.jpg',
            ],
            ['id' => '5',
            'path' => 'cg5.jpg',
            ],
            ['id' => '6',
            'path' => 'cg5.jpg',
            ],
            ['id' => '7',
            'path' => 'cg7.jpg',
            ],
            ['id' => '8',
            'path' => 'cg8.jpg',
            ],
            ['id' => '9',
            'path' => 'cg9.jpg',
            ],
            ['id' => '10',
            'path' => 'cg10.jpg',
            ],
            ['id' => '11',
            'path' => 'cg11.jpg',
            ],
            ['id' => '12',
            'path' => 'cg12.jpg',
            ],
            ['id' => '13',
            'path' => 'cg13.jpg',
            ],
            ['id' => '14',
            'path' => 'cg14.jpg',
            ],
            ['id' => '15',
            'path' => 'cg15.jpg',
            ],
            ['id' => '16',
            'path' => 'cg16.jpg',
            ],
            ['id' => '17',
            'path' => 'cg17.jpg',
            ],
            ['id' => '18',
            'path' => 'cg18.jpg',
            ],
            ['id' => '19',
            'path' => 'cg19.jpg',
            ],
            ['id' => '20',
            'path' => 'cg20.jpg',
            ],
            ['id' => '21',
            'path' => 'cg21.jpg',
            ],
            ['id' => '22',
            'path' => 'cg22.jpg',
            ],
            ['id' => '23',
            'path' => 'cg23.jpg',
            ],
            ['id' => '24',
            'path' => 'cg24.jpg',
            ],
            ['id' => '25',
            'path' => 'cg25.jpg',
            ],
            ['id' => '26',
            'path' => 'cg26.jpg',
            ],
            ['id' => '27',
            'path' => 'cg27.jpg',
            ],
            ['id' => '28',
            'path' => 'cg28.jpg',
            ],
            ['id' => '29',
            'path' => 'cg29.jpg',
            ],
            ['id' => '30',
            'path' => 'cg30.jpg',
            ],
            ['id' => '31',
            'path' => 'cg31.jpg',
            ],
            ['id' => '32',
            'path' => 'cg32.jpg',
            ],
            ['id' => '33',
            'path' => 'cg33.jpg',
            ],
            ['id' => '34',
            'path' => 'cg34.jpg',
            ],
            ['id' => '35',
            'path' => 'cg35.jpg',
            ],
            ['id' => '36',
            'path' => 'cg36.jpg',
            ],
            ['id' => '37',
            'path' => 'cg37.jpg',
            ],
            ['id' => '38',
            'path' => 'cg38.jpg',
            ],
            ['id' => '39',
            'path' => 'cg39.jpg',
            ],
            ['id' => '40',
            'path' => 'cg40.jpg',
            ],
            ['id' => '41',
            'path' => 'cg41.jpg',
            ],
            ['id' => '42',
            'path' => 'cg42.jpg',
            ],
            ['id' => '43',
            'path' => 'cg43.jpg',
            ],
            ['id' => '44',
            'path' => 'cg44.jpg',
            ],
            ['id' => '45',
            'path' => 'cg45.jpg',
            ],
            ['id' => '46',
            'path' => 'cg46.jpg',
            ],
            ['id' => '47',
            'path' => 'cg47.jpg',
            ],
            ['id' => '48',
            'path' => 'cg48.jpg',
            ],
            ['id' => '49',
            'path' => 'cg49.jpg',
            ],
            ['id' => '50',
            'path' => 'cg50.jpg',
            ],
            ['id' => '51',
            'path' => 'cg51.jpg',
            ],
            ['id' => '52',
            'path' => 'cg52.jpg',
            ],
            ['id' => '53',
            'path' => 'cg53.jpg',
            ],
            ['id' => '54',
            'path' => 'cg54.jpg',
            ],
            ['id' => '55',
            'path' => 'cg55.jpg',
            ],
            ['id' => '56',
            'path' => 'cg56.jpg',
            ],
            ['id' => '57',
            'path' => 'cg57.jpg',
            ],
            ['id' => '58',
            'path' => 'cg58.jpg',
            ],
            ['id' => '59',
            'path' => 'cg59.jpg',
            ],
            ['id' => '60',
            'path' => 'cg60.jpg',
            ],
            ['id' => '61',
            'path' => 'cg61.jpg',
            ],
            ['id' => '62',
            'path' => 'cg62.jpg',
            ],
            ['id' => '63',
            'path' => 'cg63.jpg',
            ],
            ['id' => '64',
            'path' => 'cg64.jpg',
            ],
            ['id' => '65',
            'path' => 'cg65.jpg',
            ],
            ['id' => '66',
            'path' => 'cg66.jpg',
            ],
            ['id' => '67',
            'path' => 'cg67.jpg',
            ],
            ['id' => '68',
            'path' => 'cg68.jpg',
            ],
            ['id' => '69',
            'path' => 'cg69.jpg',
            ],
            ['id' => '70',
            'path' => 'cg70.jpg',
            ],
            ['id' => '71',
            'path' => 'cg71.jpg',
            ],
            ['id' => '72',
            'path' => 'cg72.jpg',
            ],
            ['id' => '73',
            'path' => 'cg73.jpg',
            ],
            ['id' => '74',
            'path' => 'cg74.jpg',
            ],
            ['id' => '75',
            'path' => 'cg75.jpg',
            ],
            ['id' => '76',
            'path' => 'cg76.jpg',
            ],
            ['id' => '77',
            'path' => 'cg77.jpg',
            ],
            ['id' => '78',
            'path' => 'cg78.jpg',
            ],
            ['id' => '79',
            'path' => 'cg79.jpg',
            ],
            ['id' => '80',
            'path' => 'cg80.jpg',
            ],
            ['id' => '81',
            'path' => 'cg81.jpg',
            ],

            ]);
    }
}
