<?php

use Illuminate\Database\Seeder;

class Cg_PicturesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cg_pictures')->insert([
            ['id' => '1',
            'camp_id' => '1',
            'cg_pic_id' => '1',
            ],
            ['id' => '2',
            'camp_id' => '1',
            'cg_pic_id' => '2',
            ],
            ['id' => '3',
            'camp_id' => '1',
            'cg_pic_id' => '3',
            ],

            ['id' => '4',
            'camp_id' => '1',
            'cg_pic_id' => '4',
            ],
            ['id' => '5',
            'camp_id' => '1',
            'cg_pic_id' => '5',
            ],
            ['id' => '6',
            'camp_id' => '1',
            'cg_pic_id' => '6',
            ],

            ['id' => '7',
            'camp_id' => '1',
            'cg_pic_id' => '7',
            ],
            ['id' => '8',
            'camp_id' => '1',
            'cg_pic_id' => '8',
            ],
            ['id' => '9',
            'camp_id' => '1',
            'cg_pic_id' => '9',
            ],

            ['id' => '10',
            'camp_id' => '2',
            'cg_pic_id' => '10',
            ],
            ['id' => '11',
            'camp_id' => '2',
            'cg_pic_id' => '11',
            ],
            ['id' => '12',
            'camp_id' => '2',
            'cg_pic_id' => '12',
            ],

            ['id' => '13',
            'camp_id' => '2',
            'cg_pic_id' => '13',
            ],
            ['id' => '14',
            'camp_id' => '2',
            'cg_pic_id' => '14',
            ],
            ['id' => '15',
            'camp_id' => '2',
            'cg_pic_id' => '15',
            ],

            ['id' => '16',
            'camp_id' => '2',
            'cg_pic_id' => '16',
            ],
            ['id' => '17',
            'camp_id' => '2',
            'cg_pic_id' => '17',
            ],
            ['id' => '18',
            'camp_id' => '2',
            'cg_pic_id' => '18',
            ],

            ['id' => '19',
            'camp_id' => '3',
            'cg_pic_id' => '19',
            ],
            ['id' => '20',
            'camp_id' => '3',
            'cg_pic_id' => '20',
            ],
            ['id' => '21',
            'camp_id' => '3',
            'cg_pic_id' => '21',
            ],

            ['id' => '22',
            'camp_id' => '3',
            'cg_pic_id' => '22',
            ],
            ['id' => '23',
            'camp_id' => '3',
            'cg_pic_id' => '23',
            ],
            ['id' => '24',
            'camp_id' => '3',
            'cg_pic_id' => '24',
            ],

            ['id' => '25',
            'camp_id' => '3',
            'cg_pic_id' => '25',
            ],
            ['id' => '26',
            'camp_id' => '3',
            'cg_pic_id' => '26',
            ],
            ['id' => '27',
            'camp_id' => '3',
            'cg_pic_id' => '27',
            ],
            ['id' => '28',
            'camp_id' => '4',
            'cg_pic_id' => '28',
            ],
            ['id' => '29',
            'camp_id' => '4',
            'cg_pic_id' => '29',
            ],
            ['id' => '30',
            'camp_id' => '4',
            'cg_pic_id' => '30',
            ],

            ['id' => '31',
            'camp_id' => '4',
            'cg_pic_id' => '31',
            ],
            ['id' => '32',
            'camp_id' => '4',
            'cg_pic_id' => '32',
            ],
            ['id' => '33',
            'camp_id' => '4',
            'cg_pic_id' => '33',
            ],

            ['id' => '34',
            'camp_id' => '4',
            'cg_pic_id' => '34',
            ],
            ['id' => '35',
            'camp_id' => '4',
            'cg_pic_id' => '35',
            ],
            ['id' => '36',
            'camp_id' => '4',
            'cg_pic_id' => '36',
            ],

            ['id' => '37',
            'camp_id' => '5',
            'cg_pic_id' => '37',
            ],
            ['id' => '38',
            'camp_id' => '5',
            'cg_pic_id' => '38',
            ],
            ['id' => '39',
            'camp_id' => '5',
            'cg_pic_id' => '39',
            ],

            ['id' => '40',
            'camp_id' => '5',
            'cg_pic_id' => '40',
            ],
            ['id' => '41',
            'camp_id' => '5',
            'cg_pic_id' => '41',
            ],
            ['id' => '42',
            'camp_id' => '5',
            'cg_pic_id' => '42',
            ],

            ['id' => '43',
            'camp_id' => '5',
            'cg_pic_id' => '43',
            ],
            ['id' => '44',
            'camp_id' => '5',
            'cg_pic_id' => '44',
            ],
            ['id' => '45',
            'camp_id' => '5',
            'cg_pic_id' => '45',
            ],

            ['id' => '46',
            'camp_id' => '6',
            'cg_pic_id' => '46',
            ],
            ['id' => '47',
            'camp_id' => '6',
            'cg_pic_id' => '47',
            ],
            ['id' => '48',
            'camp_id' => '6',
            'cg_pic_id' => '48',
            ],

            ['id' => '49',
            'camp_id' => '6',
            'cg_pic_id' => '49',
            ],
            ['id' => '50',
            'camp_id' => '6',
            'cg_pic_id' => '50',
            ],
            ['id' => '51',
            'camp_id' => '6',
            'cg_pic_id' => '51',
            ],

            ['id' => '52',
            'camp_id' => '6',
            'cg_pic_id' => '52',
            ],
            ['id' => '53',
            'camp_id' => '6',
            'cg_pic_id' => '53',
            ],
            ['id' => '54',
            'camp_id' => '6',
            'cg_pic_id' => '54',
            ],
            ['id' => '55',
            'camp_id' => '7',
            'cg_pic_id' => '55',
            ],
            ['id' => '56',
            'camp_id' => '7',
            'cg_pic_id' => '56',
            ],
            ['id' => '57',
            'camp_id' => '7',
            'cg_pic_id' => '57',
            ],

            ['id' => '58',
            'camp_id' => '7',
            'cg_pic_id' => '58',
            ],
            ['id' => '59',
            'camp_id' => '7',
            'cg_pic_id' => '59',
            ],
            ['id' => '60',
            'camp_id' => '7',
            'cg_pic_id' => '60',
            ],

            ['id' => '61',
            'camp_id' => '7',
            'cg_pic_id' => '61',
            ],
            ['id' => '62',
            'camp_id' => '7',
            'cg_pic_id' => '62',
            ],
            ['id' => '63',
            'camp_id' => '7',
            'cg_pic_id' => '63',
            ],

            ['id' => '64',
            'camp_id' => '8',
            'cg_pic_id' => '64',
            ],
            ['id' => '65',
            'camp_id' => '8',
            'cg_pic_id' => '65',
            ],
            ['id' => '66',
            'camp_id' => '8',
            'cg_pic_id' => '66',
            ],

            ['id' => '67',
            'camp_id' => '8',
            'cg_pic_id' => '67',
            ],
            ['id' => '68',
            'camp_id' => '8',
            'cg_pic_id' => '68',
            ],
            ['id' => '69',
            'camp_id' => '8',
            'cg_pic_id' => '69',
            ],

            ['id' => '70',
            'camp_id' => '8',
            'cg_pic_id' => '70',
            ],
            ['id' => '71',
            'camp_id' => '8',
            'cg_pic_id' => '71',
            ],
            ['id' => '72',
            'camp_id' => '8',
            'cg_pic_id' => '72',
            ],

            ['id' => '73',
            'camp_id' => '9',
            'cg_pic_id' => '73',
            ],
            ['id' => '74',
            'camp_id' => '9',
            'cg_pic_id' => '74',
            ],
            ['id' => '75',
            'camp_id' => '9',
            'cg_pic_id' => '75',
            ],

            ['id' => '76',
            'camp_id' => '9',
            'cg_pic_id' => '76',
            ],
            ['id' => '77',
            'camp_id' => '9',
            'cg_pic_id' => '77',
            ],
            ['id' => '78',
            'camp_id' => '9',
            'cg_pic_id' => '78',
            ],

            ['id' => '79',
            'camp_id' => '9',
            'cg_pic_id' => '79',
            ],
            ['id' => '80',
            'camp_id' => '9',
            'cg_pic_id' => '80',
            ],
            ['id' => '81',
            'camp_id' => '9',
            'cg_pic_id' => '81',
            ],

            ]);
    }
}
