<?php

use Illuminate\Database\Seeder;

class FacilitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('facilities')->insert([
            ['id' => '1',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '2',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '3',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '4',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '5',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '6',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '7',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '8',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '9',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '10',
            'camp_id' => '1',
            'css_numbers' => '0',
            ], 
            ['id' => '11',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '12',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '13',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '14',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '15',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '16',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '17',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '18',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '19',
            'camp_id' => '1',
            'css_numbers' => '1',
            ],
            ['id' => '20',
            'camp_id' => '1',
            'css_numbers' => '0',
            ],
            ['id' => '21',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '22',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '23',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '24',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '25',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '26',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '27',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '28',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '29',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '30',
            'camp_id' => '2',
            'css_numbers' => '0',
            ], 
            ['id' => '31',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '32',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '33',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '34',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '35',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '36',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '37',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '38',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '39',
            'camp_id' => '2',
            'css_numbers' => '1',
            ],
            ['id' => '40',
            'camp_id' => '2',
            'css_numbers' => '0',
            ],
            ['id' => '41',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '42',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '43',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '44',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '45',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '46',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '47',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '48',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '49',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '50',
            'camp_id' => '3',
            'css_numbers' => '0',
            ], 
            ['id' => '51',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '52',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '53',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '54',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '55',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '56',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '57',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '58',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '59',
            'camp_id' => '3',
            'css_numbers' => '1',
            ],
            ['id' => '60',
            'camp_id' => '3',
            'css_numbers' => '0',
            ],
            ['id' => '61',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '62',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '63',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '64',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '65',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '66',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '67',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '68',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '69',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '70',
            'camp_id' => '4',
            'css_numbers' => '0',
            ], 
            ['id' => '71',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '72',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '73',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '74',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '75',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '76',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '77',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '78',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '79',
            'camp_id' => '4',
            'css_numbers' => '1',
            ],
            ['id' => '80',
            'camp_id' => '4',
            'css_numbers' => '0',
            ],
            ['id' => '81',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '82',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '83',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '84',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '85',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '86',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '87',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '88',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '89',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '90',
            'camp_id' => '5',
            'css_numbers' => '0',
            ], 
            ['id' => '91',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '92',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '93',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '94',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '95',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '96',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '97',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '98',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '99',
            'camp_id' => '5',
            'css_numbers' => '1',
            ],
            ['id' => '100',
            'camp_id' => '5',
            'css_numbers' => '0',
            ],
            ['id' => '101',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '102',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '103',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '104',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '105',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '106',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '107',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '108',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '109',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '110',
            'camp_id' => '6',
            'css_numbers' => '0',
            ], 
            ['id' => '111',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '112',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '113',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '114',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '115',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '116',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '117',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '118',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '119',
            'camp_id' => '6',
            'css_numbers' => '1',
            ],
            ['id' => '120',
            'camp_id' => '6',
            'css_numbers' => '0',
            ],
            ['id' => '121',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '122',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '123',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '124',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '125',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '126',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '127',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '128',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '129',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '130',
            'camp_id' => '7',
            'css_numbers' => '0',
            ], 
            ['id' => '131',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '132',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '133',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '134',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '135',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '136',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '137',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '138',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '139',
            'camp_id' => '7',
            'css_numbers' => '1',
            ],
            ['id' => '140',
            'camp_id' => '7',
            'css_numbers' => '0',
            ],
            ['id' => '141',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '142',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '143',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '144',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '145',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '146',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '147',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '148',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '149',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '150',
            'camp_id' => '8',
            'css_numbers' => '0',
            ], 
            ['id' => '151',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '152',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '153',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '154',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '155',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '156',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '157',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '158',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '159',
            'camp_id' => '8',
            'css_numbers' => '1',
            ],
            ['id' => '160',
            'camp_id' => '8',
            'css_numbers' => '0',
            ],
            ['id' => '161',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '162',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '163',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '164',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '165',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '166',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '167',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '168',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '169',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '170',
            'camp_id' => '9',
            'css_numbers' => '0',
            ], 
            ['id' => '171',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '172',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '173',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '174',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '175',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '176',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '177',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '178',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            ['id' => '179',
            'camp_id' => '9',
            'css_numbers' => '1',
            ],
            ['id' => '180',
            'camp_id' => '9',
            'css_numbers' => '0',
            ],
            
            
            
            

            ]);
    }
}
